[package]
name = "upstox-rust-sdk"
version = "2.0.0"
edition = "2024"
authors = ["Aviral Omar", "aviralomar0301@gmail.com"]
categories = ["api-bindings", "asynchronous"]
description = "SDK to access Upstox's Uplink APIs programmatically"
keywords = ["upstox", "uplink", "sdk"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/Aviral-Omar/upstox-rust-sdk"

[dependencies]
async-imap = { version = "0.11.2", default-features = false, features = ["runtime-tokio"] }
async-native-tls = { version = "0.6.0", default-features = false, features = ["runtime-tokio"] }
async-trait = "0.1.89"
chrono = "0.4.44"
ezsockets = { version = "0.7.1", features = ["native-tls"] }
fantoccini = "0.22.1"
flate2 = "1.1.9"
futures = "0.3.32"
mailparse = "0.16.1"
protobuf = "3.7.2"
regex = "1.12.3"
reqwest = { version = "0.13.2", features = ["form", "json", "query"] }
scraper = "0.26.0"
serde = "1.0.228"
serde_json = "1.0.149"
serde_valid = "2.0.1"
serde_with = "3.18.0"
tokio = { version = "1.52.1", features = ["full"] }
tokio-cron-scheduler = { version = "0.15.1", features = ["signal"] }
tracing = "0.1.44"
url_open = "0.0.2"
urlencoding = "2.1.3"

[build-dependencies]
protobuf-codegen = "3.7.2"
